"""

Revision ID: 607da5cc3f56
Revises: 6fc66f02f8df
Create Date: 2026-06-22 15:20:02.731718

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "607da5cc3f56"
down_revision: str | Sequence[str] | None = "6fc66f02f8df"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
