from typing import TypedDict

from langgraph.graph import StateGraph, END

from langchain_ollama import ChatOllama

from youtube_transcript_api import YouTubeTranscriptApi

from integrations.youtube import YouTubeIntegration


# Graph state definition.
#
# Every node receives this state as input:
#
# {
#     "video_id": "...",
#     "transcript": "...",
#     "summary": "..."
# }
#
# Nodes can read existing fields and return updates.
class State(TypedDict):
    # Input provided when graph starts.
    video_id: str

    # Will be populated by get_transcript_node.
    transcript: str

    # Will be populated by summarize_node.
    summary: str


# Create Ollama LLM instance.
#
# temperature=0 makes output more deterministic.
llm = ChatOllama(
    model="llama3.1",
    temperature=0,
)


# First graph node.
#
# Purpose:
# Fetch transcript using video_id.
#
# Input state:
# {
#     "video_id": "abc123"
# }
#
# Output:
# {
#     "transcript": "..."
# }
#
# LangGraph will merge returned values into state.
async def get_transcript_node(state: State) -> dict[str, str] | None:

    # Create integration instance.
    youtube_integration = YouTubeIntegration()

    # Fetch transcript text for provided video.
    transcript = await youtube_integration.fetch_transcript_text(
        video_id=state["video_id"]
    )

    # If transcript not found,
    # stop by returning None.
    #
    # NOTE:
    # This may not be ideal.
    # In LangGraph it's usually better to:
    # - raise exception
    # - or return status field
    # - or use conditional routing
    if not transcript:
        return None

    # Return state update.
    #
    # LangGraph merges:
    #
    # Before:
    # {
    #     "video_id": "abc123"
    # }
    #
    # After:
    # {
    #     "video_id": "abc123",
    #     "transcript": "..."
    # }
    return {"transcript": transcript}


# Second graph node.
#
# Purpose:
# Generate summary from transcript.
#
# Input state:
# {
#     "video_id": "...",
#     "transcript": "..."
# }
#
# Output:
# {
#     "summary": "..."
# }
async def summarize_node(state: State) -> dict[str, str]:

    # Prompt sent to LLM.
    #
    # Uses transcript generated by previous node.
    prompt = f"""
Summarize the following YouTube video.

Transcript:

{state["transcript"]}

Provide:
1. Short summary
2. Main topics
3. Key takeaways
"""

    # Asynchronously invoke Ollama.
    response = await llm.ainvoke(prompt)

    # Return summary as state update.
    #
    # Before:
    # {
    #     "video_id": "...",
    #     "transcript": "..."
    # }
    #
    # After:
    # {
    #     "video_id": "...",
    #     "transcript": "...",
    #     "summary": "..."
    # }
    return {"summary": response.content}


# Create graph builder.
#
# StateGraph knows that all nodes operate
# on State objects.
graph = StateGraph(State)


# Register first node.
#
# Node name:
# "get_transcript"
#
# Function:
# get_transcript_node
graph.add_node(
    "get_transcript",
    get_transcript_node,
)


# Register second node.
#
# Node name:
# "summarize"
#
# Function:
# summarize_node
graph.add_node(
    "summarize",
    summarize_node,
)


# Define graph starting point.
#
# Execution begins here.
graph.set_entry_point("get_transcript")


# Create fixed edge:
#
# get_transcript
#       ↓
# summarize
#
# After transcript node completes,
# summarize node always runs.
graph.add_edge(
    "get_transcript",
    "summarize",
)


# Create terminal edge:
#
# summarize
#      ↓
#     END
#
# After summary generation,
# graph execution stops.
graph.add_edge(
    "summarize",
    END,
)


# Compile graph into executable application.
#
# This validates graph structure and creates
# runnable graph object.
app = graph.compile()
